name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker version
          echo ${{ secrets.ALIYUNCS_USERNAME }}
          echo ${{ secrets.ALIYUNCS_PASSWORD }}
          
          # 登录阿里云镜像仓库
          docker login --username=${{secrets.ALIYUNCS_USERNAME}} --password=${{secrets.ALIYUNCS_PASSWORD}} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile_ollama --tag registry.cn-hangzhou.aliyuncs.com/jiro-jlzhang/common:ollama
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/jiro-jlzhang/common:ollama
