name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: '.'
          filenames: |
            env
          quiet: false
          if-file-not-found: error

      - name: Build the Docker image
        run: |
          echo $IMAGE
          src_image_name = $IMAGE
          desc_image_name = ${src_image_name//:/-}

          # 登录阿里云镜像仓库
          docker login --username=${{secrets.ALIYUNCS_USERNAME}} --password=${{secrets.ALIYUNCS_PASSWORD}} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --build-arg $src_image_name --tag registry.cn-hangzhou.aliyuncs.com/jiro-jlzhang/common:$desc_image_name
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/jiro-jlzhang/common:$desc_image_name
