name: Docker pull push
on:  
  push:  
    branches:  [ main ]
    paths:
      - 'images.txt'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          # 登录阿里云镜像仓库
          docker login --username=${{secrets.ALIYUNCS_USERNAME}} --password=${{secrets.ALIYUNCS_PASSWORD}} registry.cn-hangzhou.aliyuncs.com
          
          # 遍历 images.txt 进行pull push
          while IFS= read -r img; do
            OLD_IMAGE=$img
            NEW_IMAGE_VERSION=$(echo "$OLD_IMAGE" | sed 's/[/:]/-/g')
            NEW_IMAGE=registry.cn-hangzhou.aliyuncs.com/jiro-jlzhang/common:$NEW_IMAGE_VERSION
            

            echo "Pulling image: $OLD_IMAGE"
            docker pull $OLD_IMAGE

            echo "Tagging image: $NEW_IMAGE"
            docker tag $OLD_IMAGE $NEW_IMAGE

            echo "Pushing image: $NEW_IMAGE"
            docker push $NEW_IMAGE

            log1="${OLD_IMAGE} -> ${NEW_IMAGE}\n"
            echo "$log1" > log.txt
          done < images.txt
          cat log.txt
